class Config():
    SEARCH_URL = 'https://yts.mx/search-movies'

    QUALITY = {
        "all":"all",
        "480p":"480p",
        "720p":"720p",
        "1080p":"1080p",
        "1080p.x265":"1080p.x265",
        "2160p":"2160p",
        "3D":"3D"
    }

    GENRES = {
        "all": "all",
        "action": "action",
        "adventure": "adventure",
        "animation": "animation",
        "biography": "biography",
        "comedy": "comedy",
        "crime": "crime",
        "documentary": "documentary",
        "drama": "drama",
        "family": "family",
        "fantasy": "fantasy",
        "film-noir": "film-noir",
        "game-show": "game-show",
        "history": "history",
        "horror": "horror",
        "music": "music",
        "musical": "musical",
        "mystery": "mystery",
        "news": "news",
        "reality-tv": "reality-tv",
        "romance": "romance",
        "sci-fi": "sci-fi",
        "sport": "sport",
        "talk-show": "talk-show",
        "thriller": "thriller",
        "war": "war",
        "western": "western",
    }

    RATINGS = {
        0: "all",
        1: "1+",
        2: "2+",
        3: "3+",
        4: "4+",
        5: "5+",
        6: "6+",
        7: "7+",
        8: "8+",
        9: "9+",
    }

    YEAR = {
        "0":"All",
        "2025":"2025",
        "2024": "2024",
        "2020-2025":"2020-now",
        "2010-2025": "2010-now",
        "2010-2019": "2010-2019",
        "2000-2009": "2000-2009",
        "1990-1999": "1990-1999",
        "1980-1989": "1980-1989",
        "1970-1979": "1970-1979",
        "1950-1969": "1950-1969",
        "1900-1949": "1900-1949"
    }

    LANGUAGE = {
        "en":" English",
        "foreign":" Foreign",
        "all":" selectedAll",
        "fr":" French",
        "ja":" Japanese",
        "es":" Spanish",
        "it":" Italian",
        "de":" German",
        "zh":" Chinese",
        "ko":" Korean",
        "hi":" Hindi",
        "cn":" Cantonese",
        "sv":" Swedish",
        "pt":" Portuguese",
        "ro":" Romanian",
        "ru":" Russian",
        "tr":" Turkish",
        "pl":" Polish",
        "nl":" Dutch",
        "th":" Thai",
        "da":" Danish",
        "id":" Indonesian",
        "ta":" Tamil",
        "no":" Norwegian",
        "te":" Telugu",
        "ar":" Arabic",
        "fi":" Finnish",
        "cs":" Czech",
        "tl":" Tagalog",
        "hu":" Hungarian",
        "vi":" Vietnamese",
        "fa":" Persian",
        "he":" Hebrew",
        "ml":" Malayalam",
        "pa":" Punjabi",
        "uk":" Ukrainian",
        "et":" Estonian",
        "el":" Greek",
        "bn":" Bangla",
        "ms":" Malay",
        "kn":" Kannada",
        "ca":" Catalan",
        "sk":" Slovak",
        "is":" Icelandic",
        "mr":" Marathi",
        "ur":" Urdu",
        "sr":" Serbian",
        "xx":" xx",
        "lt":" Lithuanian",
        "lv":" Latvian",
        "ka":" Georgian",
        "hr":" Croatian",
        "af":" Afrikaans",
        "bg":" Bulgarian",
        "sh":" Serbooption",
        "zu":" Zulu",
        "bs":" Bosnian",
        "mk":" Macedonian",
        "gl":" Galician",
        "wo":" Wolof",
        "ku":" Kurdish",
        "eu":" Basque",
        "ga":" Irish",
        "kk":" Kazakh",
        "sq":" Albanian",
        "bo":" Tibetan",
        "yo":" Yoruba",
        "gu":" Gujarati",
        "sw":" Swahili",
        "sl":" Slovenian",
        "am":" Amharic",
        "dz":" Dzongkha",
        "km":" Khmer",
        "mn":" Mongolian",
        "yi":" Yiddish",
        "ps":" Pashto",
        "ht":" Haitianoption",
        "st":" Southernoption",
        "hy":" Armenian",
        "cmn":" cmn",
        "yue":" Cantonese",
        "xh":" Xhosa",
        "ne":" Nepali",
        "jv":" Javanese",
        "mo":" Romanian",
        "ab":" Abkhazian",
        "la":" Latin",
        "os":" Ossetic",
        "mi":" Maori",
        "ak":" Akan",
        "ig":" Igbo",
        "cy":" Welsh",
        "mt":" Maltese",
        "my":" Burmese",
        "lo":" Lao",
        "bm":" Bambara",
        "se":" Northernoption",
        "nb":" Norwegianoption",
        "aa":" Afar",
        "lb":" Luxembourgish",
        "ky":" Kyrgyz",
        "az":" Azerbaijani",
        "so":" Somali",
        "iu":" Inuktitut",
        "lg":" Ganda",
        "be":" Belarusian",
        "zxx":" No",
        "fil":" Filipino",
        "tw":" Twi",
        "rw":" Kinyarwanda",
        "or":" Odia",
        "ase":" American",
        "nan":" Min",
        "ber":" ber",
        "qag":" qag",
        "gsw":" Swissoption",
        "ln":" Lingala",
        "iba":" Iban",
        "cr":" Cree",
        "tn":" Tswana",
        "qab":" qab",
        "rom":" Romany",
        "sa":" Sanskrit",
        "ukl":" ukl",
        "ug":" Uyghur",
        "kvk":" kvk",
        "om":" Oromo",
        "myn":" myn",
        "uz":" Uzbek",
        "ff":" Fulah",
        "fy":" Westernoption",
        "rup":" Aromanian",
        "ti":" Tigrinya",
    }

    ORDER_BY = {
        "latest": "selected",
        "oldest": "Oldest",
        "featured": "Featured",
        "seeds": "Seeds",
        "peers": "Peers",
        "year": "Year",
        "rating": "IMDb",
        "likes": "YTS",
        "rt_audience": "RT",
        "alphabetical": "Alphabetical",
        "downloads": "Downloads",                    
    }